Inventory
-------------
SELECT
ECT.CATEGORY_NAME AS "Category_Name",
ESIB.ITEM_NUMBER AS "Item Number",
ESIB.INVENTORY_ITEM_STATUS_CODE AS "Item Status",
IOP.ORGANIZATION_CODE AS "Organization Code",
ISV.SECONDARY_INVENTORY_NAME AS "Sub Inventory Name"

FROM
EGP_CATEGORIES_TL ECT,
EGP_ITEM_CATEGORIES EIC,
EGP_SYSTEM_ITEMS_B ESIB,
INV_ORG_PARAMETERS IOP,
INV_SECONDARY_INVENTORIES ISV

WHERE
ECT.CATEGORY_ID = EIC.CATEGORY_ID
AND EIC.INVENTORY_ITEM_ID = ESIB.INVENTORY_ITEM_ID
AND IOP.ORGANIZATION_ID NOT IN (300000002976252)
AND IOP.ORGANIZATION_ID=ESIB.ORGANIZATION_ID
AND ESIB.ORGANIZATION_ID = ISV.ORGANIZATION_ID
AND ESIB.INVENTORY_ITEM_STATUS_CODE='Active'
AND IOP.ORGANIZATION_CODE=NVL( :V_ORGANIZATION_CODE,IOP.ORGANIZATION_CODE)
AND ISV.SECONDARY_INVENTORY_NAME = NVL( :P_INV_NAME,ISV.SECONDARY_INVENTORY_NAME)

GROUP BY
ECT.CATEGORY_NAME,
ESIB.ITEM_NUMBER,
IOP.ORGANIZATION_CODE,
ISV.SECONDARY_INVENTORY_NAME,
ESIB.INVENTORY_ITEM_STATUS_CODE


======================================================
SUPPLIER
-----------

SELECT 
  PSV.VENDOR_NAME as "Supplier_name",
  PSV.SEGMENT1 as "Supplier_number",
  TAX_PRF.REP_REGISTRATION_NUMBER "REGISTRATION_NUMBER",
  PSAV.PARTY_SITE_NAME "Supplier Address Name",
  PSAV.ADDRESS1 ,
  PSAV.ADDRESS2 ,
  PSAV.ADDRESS3 ,
  PSAV.ADDRESS4 ,
  PSAV.CITY ,
  PSAV.STATE ,
  PSAV.COUNTY ,
  PSAV.POSTAL_CODE ,
  PSAV.COUNTRY ,
  PSAV.EMAIL_ADDRESS ,
  PSSV.VENDOR_SITE_CODE ,
  PSSV.INVOICE_CURRENCY_CODE ,
  HP.PARTY_NAME BANK_PARTY_NAME,
  IEBA.COUNTRY_CODE BANK_COUNTRY,
  IEBA.BANK_ACCOUNT_NUM BANK_ACCOUNT_NUM,
  HP.PARTY_NAME BANK_ACCOUNT_NAME,
  IEBA.CURRENCY_CODE BANK_ACCT_CURRENCY_CODE,
  IEBA.IBAN ,
  EBB.BANK_BRANCH_NAME ,
  EBB.BRANCH_NUMBER,
  HRO.NAME AS BU_NAME

  

FROM POZ_SUPPLIERS_V PSV ,
  POZ_SUPPLIERS_PII PSP,
  ZX_PARTY_TAX_PROFILE TAX_PRF,
  FND_LOOKUP_VALUES_TL REGT,
  HZ_CODE_ASSIGNMENTS HCA,
  FND_LOOKUP_VALUES_TL HCAVAL,
  ZX_REGISTRATIONS ZXR,
  POZ_SUPPLIER_SITES_V PSSV,
  POZ_ALL_SUPPLIER_CONTACTS_V PSC,
  HZ_RELATIONSHIPS hr,
  HZ_ORG_CONTACTS hoc,
  IBY_EXTERNAL_PAYEES_ALL IEPA,
  IBY_EXT_PARTY_PMT_MTHDS IEPPM,
  IBY_PMT_INSTR_USES_ALL IPIUA ,
  IBY_EXT_BANK_ACCOUNTS IEBA,
   CE_BANK_BRANCHES_V EBB,
  HZ_PARTIES HP,
  IBY_EXTERNAL_PAYEES_ALL BANK,
  POZ_SUPPLIER_ADDRESS_V PSAV,
  AP_TERMS_TL TERMS,
  POZ_SITE_ASSIGNMENTS_ALL_M PSAA,
  HR_OPERATING_UNITS HRO,
  HR_OPERATING_UNITS HRO1,
  IBY_EXT_PARTY_PMT_MTHDS PAY_METHOD
 
WHERE PSP.VENDOR_ID(+)               =PSV.VENDOR_ID
AND TAX_PRF.PARTY_ID(+)                =PSV.PARTY_ID
AND TAX_PRF.PARTY_TAX_PROFILE_ID       = HCA.OWNER_TABLE_ID(+)
AND (HCA.OWNER_TABLE_NAME          = 'ZX_PARTY_TAX_PROFILE'
OR HCA.OWNER_TABLE_NAME           IS NULL)
AND HCAVAL.LOOKUP_CODE(+)          =HCA.CLASS_CODE
AND (REGT.LOOKUP_TYPE              ='ZX_REGISTRATIONS_TYPE'
OR REGT.LOOKUP_TYPE               IS NULL)
AND TAX_PRF.REGISTRATION_TYPE_CODE     =REGT.LOOKUP_CODE(+)
AND TAX_PRF.PARTY_TAX_PROFILE_ID       =ZXR.PARTY_TAX_PROFILE_ID(+)
AND PSSV.VENDOR_ID(+)              =PSV.VENDOR_ID
AND PSSV.VENDOR_SITE_ID            = IEPA.SUPPLIER_SITE_ID(+)
AND PSC.SUP_PARTY_ID(+)            = PSV.PARTY_ID
AND hr.subject_id(+)               =PSV.PARTY_ID
AND( hr.relationship_code          = 'CONTACT'
OR hr.relationship_code           IS NULL)
AND (hr.object_table_name          = 'HZ_PARTIES'
OR hr.object_table_name           IS NULL)
AND hoc.party_relationship_id(+)   = hr.relationship_id
AND IEPA.EXT_PAYEE_ID              = IEPPM.EXT_PMT_PARTY_ID(+)
AND ((IEPPM.INACTIVE_DATE         IS NULL)
OR (IEPPM.INACTIVE_DATE            > SYSDATE) )
AND IPIUA.EXT_PMT_PARTY_ID (+)     = IEPA.EXT_PAYEE_ID
AND ( IPIUA.INSTRUMENT_TYPE        = 'BANKACCOUNT'
OR IPIUA.INSTRUMENT_TYPE          IS NULL)
AND ( IPIUA.PAYMENT_FLOW           = 'DISBURSEMENTS'
OR IPIUA.PAYMENT_FLOW             IS NULL)
AND ( IPIUA.ORDER_OF_PREFERENCE    = 1
OR IPIUA.ORDER_OF_PREFERENCE      IS NULL)
AND IPIUA.INSTRUMENT_ID            = IEBA.EXT_BANK_ACCOUNT_ID(+)
AND HP.PARTY_ID (+)                = IEBA.BANK_ID
AND IEBA.BRANCH_ID                 = EBB.BRANCH_PARTY_ID(+)
AND BANK.EXT_PAYEE_ID(+)           =PSV.VENDOR_ID
AND PSAV.LOCATION_ID(+)            =PSSV.LOCATION_ID
AND TERMS.TERM_ID(+)               =PSSV.TERMS_ID
AND PSAA.VENDOR_SITE_ID(+)         =PSSV.VENDOR_SITE_ID
AND HRO.ORGANIZATION_ID(+)         =PSAA.BU_ID
AND HRO1.ORGANIZATION_ID(+)        =PSAA.BILL_TO_BU_ID
AND PAY_METHOD.EXT_PMT_PARTY_ID(+) =BANK.EXT_PAYEE_ID
AND BANK.EXT_PAYEE_ID              =PAY_METHOD.EXT_PMT_PARTY_ID(+)
AND HP.STATUS = 'A'
--AND PSV.VENDOR_ID=300000041708662
group by
  PSV.VENDOR_NAME,
  PSV.SEGMENT1,
  TAX_PRF.REP_REGISTRATION_NUMBER,
  PSAV.PARTY_SITE_NAME,
  PSAV.ADDRESS1 ,
  PSAV.ADDRESS2 ,
  PSAV.ADDRESS3 ,
  PSAV.ADDRESS4 ,
  PSAV.CITY ,
  PSAV.STATE ,
  PSAV.COUNTY ,
  PSAV.POSTAL_CODE ,
  PSAV.COUNTRY ,
  PSAV.EMAIL_ADDRESS ,
  PSSV.VENDOR_SITE_CODE ,
  PSSV.INVOICE_CURRENCY_CODE ,
  HP.PARTY_NAME,
  IEBA.COUNTRY_CODE,
  IEBA.BANK_ACCOUNT_NUM,
  HP.PARTY_NAME,
  IEBA.CURRENCY_CODE,
  IEBA.IBAN ,
  EBB.BANK_BRANCH_NAME ,
  EBB.BRANCH_NUMBER,
  HRO.NAME
  order by
  PSV.SEGMENT1
  
  
=======================================================
  Bank detail
  ------------
  SELECT
  PSV.VENDOR_NAME as "Supplier_name",
  PSV.SEGMENT1 as "Supplier_number",
  TAX_PRF.REP_REGISTRATION_NUMBER "REGISTRATION_NUMBER",
  PSAV.PARTY_SITE_NAME "Supplier Address Name",
  PSAV.ADDRESS1 ,
  PSAV.ADDRESS2 ,
  PSAV.ADDRESS3 ,
  PSAV.ADDRESS4 ,
  PSAV.CITY ,
  PSAV.STATE ,
  HP.COUNTY ,
  PSAV.POSTAL_CODE ,
  PSAV.COUNTRY ,
  PSAV.EMAIL_ADDRESS ,
  PSSV.VENDOR_SITE_CODE ,
  PSSV.INVOICE_CURRENCY_CODE ,
  HP.PARTY_NAME BANK_PARTY_NAME,
  IEBA.COUNTRY_CODE BANK_COUNTRY,
  IEBA.BANK_ACCOUNT_NUM BANK_ACCOUNT_NUM,
  HP.PARTY_NAME BANK_ACCOUNT_NAME,
  IEBA.CURRENCY_CODE BANK_ACCT_CURRENCY_CODE,
  IEBA.IBAN ,
  EBB.BANK_BRANCH_NAME ,
  EBB.BRANCH_NUMBER,
  EBB.BANK_NAME,
  EBB.BANK_NUMBER,
  EBB.EFT_SWIFT_CODE AS BIC,
  HRO.NAME AS BU_NAME,
  HP1.PARTY_NAME AS LEGAL_ENTITY_NAME

  FROM POZ_SUPPLIERS_V PSV ,
  POZ_SUPPLIERS_PII PSP,
  ZX_PARTY_TAX_PROFILE TAX_PRF,
  FND_LOOKUP_VALUES_TL REGT,
  HZ_CODE_ASSIGNMENTS HCA,
  FND_LOOKUP_VALUES_TL HCAVAL,
  ZX_REGISTRATIONS ZXR,
  POZ_SUPPLIER_SITES_V PSSV,
  POZ_ALL_SUPPLIER_CONTACTS_V PSC,
  HZ_RELATIONSHIPS hr,
  HZ_ORG_CONTACTS hoc,
  IBY_EXTERNAL_PAYEES_ALL IEPA,
  IBY_EXT_PARTY_PMT_MTHDS IEPPM,
  IBY_PMT_INSTR_USES_ALL IPIUA ,
  IBY_EXT_BANK_ACCOUNTS IEBA,
   CE_BANK_BRANCHES_V EBB,
  HZ_PARTIES HP,
  IBY_EXTERNAL_PAYEES_ALL BANK,
  POZ_SUPPLIER_ADDRESS_V PSAV,
  AP_TERMS_TL TERMS,
  POZ_SITE_ASSIGNMENTS_ALL_M PSAA,
  HR_OPERATING_UNITS HRO,
  HR_OPERATING_UNITS HRO1,
  IBY_EXT_PARTY_PMT_MTHDS PAY_METHOD,
  XLE_ENTITY_PROFILES XEP,
  HZ_PARTIES HP1
 
WHERE PSP.VENDOR_ID(+)               =PSV.VENDOR_ID
AND TAX_PRF.PARTY_ID(+)                =PSV.PARTY_ID
AND TAX_PRF.PARTY_TAX_PROFILE_ID       = HCA.OWNER_TABLE_ID(+)
AND (HCA.OWNER_TABLE_NAME          = 'ZX_PARTY_TAX_PROFILE'
OR HCA.OWNER_TABLE_NAME           IS NULL)
AND HCAVAL.LOOKUP_CODE(+)          =HCA.CLASS_CODE
AND (REGT.LOOKUP_TYPE              ='ZX_REGISTRATIONS_TYPE'
OR REGT.LOOKUP_TYPE               IS NULL)
AND TAX_PRF.REGISTRATION_TYPE_CODE     =REGT.LOOKUP_CODE(+)
AND TAX_PRF.PARTY_TAX_PROFILE_ID       =ZXR.PARTY_TAX_PROFILE_ID(+)
AND PSSV.VENDOR_ID(+)              =PSV.VENDOR_ID
AND PSSV.VENDOR_SITE_ID            = IEPA.SUPPLIER_SITE_ID(+)
AND PSC.SUP_PARTY_ID(+)            = PSV.PARTY_ID
AND hr.subject_id(+)               =PSV.PARTY_ID
AND( hr.relationship_code          = 'CONTACT'
OR hr.relationship_code           IS NULL)
AND (hr.object_table_name          = 'HZ_PARTIES'
OR hr.object_table_name           IS NULL)
AND hoc.party_relationship_id(+)   = hr.relationship_id
AND IEPA.EXT_PAYEE_ID              = IEPPM.EXT_PMT_PARTY_ID(+)
AND ((IEPPM.INACTIVE_DATE         IS NULL)
OR (IEPPM.INACTIVE_DATE            > SYSDATE) )
AND IPIUA.EXT_PMT_PARTY_ID (+)     = IEPA.EXT_PAYEE_ID
AND ( IPIUA.INSTRUMENT_TYPE        = 'BANKACCOUNT'
OR IPIUA.INSTRUMENT_TYPE          IS NULL)
AND ( IPIUA.PAYMENT_FLOW           = 'DISBURSEMENTS'
OR IPIUA.PAYMENT_FLOW             IS NULL)
AND ( IPIUA.ORDER_OF_PREFERENCE    = 1
OR IPIUA.ORDER_OF_PREFERENCE      IS NULL)
AND IPIUA.INSTRUMENT_ID            = IEBA.EXT_BANK_ACCOUNT_ID(+)
AND HP.PARTY_ID (+)                = IEBA.BANK_ID
AND IEBA.BRANCH_ID                 = EBB.BRANCH_PARTY_ID(+)
AND BANK.EXT_PAYEE_ID(+)           =PSV.VENDOR_ID
AND PSAV.LOCATION_ID(+)            =PSSV.LOCATION_ID
AND TERMS.TERM_ID(+)               =PSSV.TERMS_ID
AND PSAA.VENDOR_SITE_ID(+)         =PSSV.VENDOR_SITE_ID
AND HRO.ORGANIZATION_ID(+)         =PSAA.BU_ID
AND HRO1.ORGANIZATION_ID(+)        =PSAA.BILL_TO_BU_ID
AND PAY_METHOD.EXT_PMT_PARTY_ID(+) =BANK.EXT_PAYEE_ID
AND BANK.EXT_PAYEE_ID              =PAY_METHOD.EXT_PMT_PARTY_ID(+)
AND HP1.PARTY_ID = XEP.PARTY_ID
AND HP.STATUS = 'A'
--AND PSV.VENDOR_ID=300000041708662
group by
 PSV.VENDOR_NAME,
  PSV.SEGMENT1,
  TAX_PRF.REP_REGISTRATION_NUMBER,
  PSAV.PARTY_SITE_NAME,
  PSAV.ADDRESS1 ,
  PSAV.ADDRESS2 ,
  PSAV.ADDRESS3 ,
  PSAV.ADDRESS4 ,
  PSAV.CITY ,
  PSAV.STATE ,
  HP.COUNTY ,
  PSAV.POSTAL_CODE ,
  PSAV.COUNTRY ,
  PSAV.EMAIL_ADDRESS ,
  PSSV.VENDOR_SITE_CODE ,
  PSSV.INVOICE_CURRENCY_CODE ,
  HP.PARTY_NAME,
  IEBA.COUNTRY_CODE,
  IEBA.BANK_ACCOUNT_NUM,
  HP.PARTY_NAME,
  IEBA.CURRENCY_CODE,
  IEBA.IBAN ,
  EBB.BANK_BRANCH_NAME ,
  EBB.BRANCH_NUMBER,
  EBB.BANK_NAME,
  EBB.BANK_NUMBER,
  EBB.EFT_SWIFT_CODE,
  HRO.NAME,
  HP1.PARTY_NAME
==================================================================
  PR TO PO CONVERSION
  --------------------
 1. AVG QUERY
  --------
  SELECT 
round(avg(A.PR_TO_PO_Conversion),1) avg_con,
       A.PO_MONTH,
	   substr(A.PO_MONTH,1,3) MONTHS,
	   -- A.MON_NUM,
	   decode(A.MON_NUM,10,9.1,11,9.2,12,9.3,A.MON_NUM) mon_num,
	   A.BUYER
	   
FROM (select 

TO_CHAR(poh.creation_date,'DD/MM/YYYY') Po_Creation_Date
,poh.segment1 Order_number
,pol.LINE_NUM LINE
-- ,pol.ITEM_DESCRIPTION line_description
,TRIM(translate(translate(pol.ITEM_DESCRIPTION, chr(10)||chr(11)||chr(13), ' '), chr(9), ' ')) line_description
,hzp.vendor_name SUPPLIER
,POR.Requisition_number PR_Number
-- ,TO_CHAR(POR.APPROVED_DATE,'DD/MM/YYYY') PR_Issue_Date
,TO_CHAR(POR.CREATION_DATE,'DD/MM/YYYY') PR_Issue_Date
,(SELECT ITEM_NUMBER FROM EGP_SYSTEM_ITEMS WHERE INVENTORY_ITEM_ID = POL.ITEM_ID AND ROWNUM =1) ITEM
,egpc.category_name CATEGORY_NAME
,buy.DISPLAY_NAME BUYER
-- ,( TO_DATE(TO_CHAR(poh.creation_date,'DD/MM/YYYY'),'DD/MM/YYYY') - TO_DATE(TO_CHAR(POR.APPROVED_DATE,'DD/MM/YYYY'),'DD/MM/YYYY') ) PR_TO_PO_Conversion
,(TO_DATE(TO_CHAR(poh.creation_date,'DD/MM/YYYY'),'DD/MM/YYYY') - TO_DATE(TO_CHAR(POR.CREATION_DATE,'DD/MM/YYYY'),'DD/MM/YYYY') ) PR_TO_PO_Conversion
,TO_CHAR(poh.creation_date,'Mon-YYYY', 'nls_date_language = english') po_month
,TO_NUMBER( TO_CHAR( poh.creation_date, 'mon' ) ) mon_num
,IOP.ORGANIZATION_CODE INV_ORG
,(select distinct PERIOD_YEAR from gl_periods
where PERIOD_YEAR =  TO_CHAR(poh.creation_date,'YYYY')) period_year 

From

PO_HEADERS_ALL Poh
,PO_LINES_ALL pol
,POZ_SUPPLIERS_V hzp
,POR_REQUISITION_HEADERS_ALL POR
,POR_REQUISITION_LINES_ALL PORL
--EGP_SYSTEM_ITEMS_B egp
,EGP_CATEGORIES_VL egpc
,PER_PERSON_NAMES_F_V buy
,INV_ORG_PARAMETERS IOP
,PO_DISTRIBUTIONS_ALL PDA 
,POR_REQ_DISTRIBUTIONS_ALL PRDA
,PO_LINE_LOCATIONS_ALL PLLA

where 1=1
 and     poh.PO_HEADER_ID  = pol.PO_HEADER_ID
 and pda.po_header_id=pol.po_header_id
 and pda.po_line_id=pol.po_line_id
 and  PDA.req_distribution_id = PRDA.distribution_id
 and PRDA.REQUISITION_LINE_ID = PORL.REQUISITION_LINE_ID
 and PORL.REQUISITION_HEADER_ID = POR.REQUISITION_HEADER_ID
  and	 poh.VENDOR_ID     = hzp.VENDOR_ID
  --and  pol.ITEM_ID=egp.INVENTORY_ITEM_ID
 and	 egpc.CATEGORY_ID =pol.CATEGORY_ID
 and	 poh.AGENT_ID = buy.PERSON_ID
 --AND   IOP.ORGANIZATION_ID = egp.ORGANIZATION_ID  
 AND PLLA.PO_HEADER_ID=PDA.PO_HEADER_ID
 AND PLLA.PO_LINE_ID=PDA.PO_LINE_ID
 AND PLLA.LINE_LOCATION_ID=PDA.LINE_LOCATION_ID
 AND IOP.ORGANIZATION_ID=PLLA.SHIP_TO_ORGANIZATION_ID
 
 
 
and (egpc.category_name  IN (:P_CATEGORY_NAME) OR 'All' IN (:P_CATEGORY_NAME||'All'))

 and  (TO_CHAR(poh.creation_date,'YYYY') in  (:P_YEAR) OR 'All' IN (:P_YEAR||'All') )
 and  (TO_CHAR(poh.creation_date,'Mon', 'nls_date_language = english') in  (:P_MONTH) OR 'All' IN (:P_MONTH||'All') )
 AND (IOP.ORGANIZATION_CODE  IN (:P_INV_ORG) OR 'All' IN (:P_INV_ORG||'All'))
) A
 
 group by
 A.po_month,
 A.MON_NUM,
 A.BUYER
 
 order by 
 	   decode(A.MON_NUM,10,9.1,11,9.2,12,9.3,A.MON_NUM)
-------------------------------------
2.PO TO PR CONVERSION
--------------------------
select 
-- Distinct

TO_CHAR(poh.creation_date,'DD/MM/YYYY') Po_Creation_Date
,poh.segment1 Order_number
,pol.LINE_NUM LINE
-- ,pol.ITEM_DESCRIPTION line_description
,TRIM(translate(translate(pol.ITEM_DESCRIPTION, chr(10)||chr(11)||chr(13), ' '), chr(9), ' ')) line_description
,hzp.vendor_name SUPPLIER
,POR.Requisition_number PR_Number
-- ,TO_CHAR(POR.APPROVED_DATE,'DD/MM/YYYY') PR_Issue_Date
,TO_CHAR(POR.CREATION_DATE,'DD/MM/YYYY') PR_Issue_Date
--,egp.Item_number ITEM
,(SELECT ITEM_NUMBER FROM EGP_SYSTEM_ITEMS WHERE INVENTORY_ITEM_ID = POL.ITEM_ID AND ROWNUM =1) ITEM
,egpc.category_name CATEGORY_NAME
,buy.DISPLAY_NAME BUYER
-- ,( TO_DATE(TO_CHAR(poh.creation_date,'DD/MM/YYYY'),'DD/MM/YYYY') - TO_DATE(TO_CHAR(POR.APPROVED_DATE,'DD/MM/YYYY'),'DD/MM/YYYY') ) PR_TO_PO_Conversion
,(TO_DATE(TO_CHAR(poh.creation_date,'DD/MM/YYYY'),'DD/MM/YYYY') - TO_DATE(TO_CHAR(POR.CREATION_DATE,'DD/MM/YYYY'),'DD/MM/YYYY') ) PR_TO_PO_Conversion
,TO_CHAR(poh.creation_date,'Mon-YYYY', 'nls_date_language = english') po_month
,TO_CHAR(:P_START_DATE,'DD/MM/YYYY') start_date
,TO_CHAR(:P_END_DATE,'DD/MM/YYYY') end_date
,TO_CHAR(PORL.LAST_APPROVAL_DATE,'DD/MM/YYYY') as "PR Approval Date"

From
PO_HEADERS_ALL Poh
,PO_LINES_ALL pol
, PO_DISTRIBUTIONS_ALL PDA 
,POZ_SUPPLIERS_V hzp
,POR_REQUISITION_HEADERS_ALL POR
,POR_REQUISITION_LINES_ALL PORL
,POR_REQ_DISTRIBUTIONS_ALL PRDA
--,EGP_SYSTEM_ITEMS_B egp
,EGP_CATEGORIES_VL egpc
,PER_PERSON_NAMES_F_V buy

where 1=1
 -- and poh.segment1 = 'P011302'
 and     poh.PO_HEADER_ID  = pol.PO_HEADER_ID
 and pda.po_header_id=pol.po_header_id
 and pda.po_line_id=pol.po_line_id
 and  PDA.req_distribution_id = PRDA.distribution_id
 and PRDA.REQUISITION_LINE_ID = PORL.REQUISITION_LINE_ID
 and PORL.REQUISITION_HEADER_ID = POR.REQUISITION_HEADER_ID
 and	 poh.VENDOR_ID     = hzp.VENDOR_ID
 --and	 poh.PO_HEADER_ID  = PORL.PO_HEADER_ID 
 --and	 PORL.REQUISITION_HEADER_ID = POR.REQUISITION_HEADER_ID
 --and	 pol.ITEM_ID=egp.INVENTORY_ITEM_ID
 and	 egpc.CATEGORY_ID =pol.CATEGORY_ID
 and	 poh.AGENT_ID = buy.PERSON_ID
and NVL(:P_END_DATE,TRUNC(poh.creation_date)) between TRUNC(buy.EFFECTIVE_START_DATE)  and TRUNC(buy.EFFECTIVE_END_DATE) 
 and (buy.DISPLAY_NAME  IN (:P_BUYER) OR 'All' IN (:P_BUYER||'All'))
 and (egpc.category_name  IN (:P_CATEGORY_NAME) OR 'All' IN (:P_CATEGORY_NAME||'All'))
 and (hzp.vendor_name   IN (:P_SUPPLIER_NAME) OR 'All' IN (:P_SUPPLIER_NAME||'All'))
 and  TRUNC(poh.creation_date) BETWEEN NVL(:P_START_DATE,TRUNC(poh.creation_date)) AND NVL(:P_END_DATE,TRUNC(poh.creation_date))
 
 order by 
 TO_CHAR(POR.CREATION_DATE,'DD/MM/YYYY')	   
	   