select distinct iop.organization_code,
esib.item_number,
ioh.SUBINVENTORY_CODE,
ESIB.INVENTORY_ITEM_STATUS_CODE
,ESIB.ATTRIBUTE3
--,ECT.CATEGORY_NAME
 from 
EGP_SYSTEM_ITEMS_B ESIB,
INV_ORG_PARAMETERS IOP,
--INV_ITEM_LOCATIONS itl
INV_ONHAND_QUANTITIES_DETAIL ioh
--EGP_CATEGORIES_TL ECT,
--EGP_ITEM_CATEGORIES EIC
--EGP_CATEGORY_SETS_B ECS
where
ESIB.ORGANIZATION_ID = IOP.ORGANIZATION_ID
--and IOP.ORGANIZATION_CODE='BG'
--and esib.item_number='OT-CHEMCL-100075'
--and itl.INVENTORY_ITEM_ID(+)	=ESIB.INVENTORY_ITEM_ID
--and itl.ORGANIZATION_ID(+)=esib.ORGANIZATION_ID
and ioh.INVENTORY_ITEM_ID	=ESIB.INVENTORY_ITEM_ID
and ioh.ORGANIZATION_ID=esib.ORGANIZATION_ID
and exists (select 1 from (select sum(TRANSACTION_QUANTITY) ,inventory_item_id , organization_id from INV_ONHAND_QUANTITIES_DETAIL b
where
b.INVENTORY_ITEM_ID	=ESIB.INVENTORY_ITEM_ID
and b.ORGANIZATION_ID=esib.ORGANIZATION_ID
group by b.inventory_item_id , b.ORGANIZATION_ID
having sum(TRANSACTION_QUANTITY) <> 0)
)
AND ESIB.INVENTORY_ITEM_STATUS_CODE='Active'
AND IOP.ORGANIZATION_CODE=NVL( :V_ORGANIZATION_CODE,IOP.ORGANIZATION_CODE)
AND ioh.SUBINVENTORY_CODE = NVL( :P_INV_NAME,ioh.SUBINVENTORY_CODE)
--AND ESIB.INVENTORY_ITEM_ID = EIC.INVENTORY_ITEM_ID
--AND ESIB.ORGANIZATION_ID = EIC.ORGANIZATION_ID
--AND ECT.CATEGORY_ID = EIC.CATEGORY_ID
--AND ECT.language(+)      = USERENV('LANG')
--AND ecs.category_set_id = eic.category_set_id
--AND ecs.structure_id = ECT.structure_id