SELECT 
HAOU.NAME AS "Business Unit",
HZP.PARTY_NAME AS "Customer Name",
HZP.PARTY_NUMBER AS "Customer Number",
RACTA.TRX_NUMBER AS "INVOICE NUMBER",
TO_CHAR(RACTA.TRX_DATE,'DD-MM-YYYY') AS "Invoice Date",
TO_CHAR(ARPSA.GL_DATE,'DD-MM-YYYY') AS "Ledger Date",
TO_CHAR(ARPSA.DUE_DATE,'DD-MM-YYYY') AS "Due Date",
ARPSA.AMOUNT_DUE_ORIGINAL AS "Invoice Amount",
ARPSA.AMOUNT_DUE_REMAINING AS "Amount Remaining",
CEIL(ARPSA.AMOUNT_DUE_ORIGINAL - ARPSA.AMOUNT_DUE_REMAINING) AS "Amount Paid",
CEIL(SYSDATE - ARPSA.DUE_DATE) AS "Past Due Days",
CASE WHEN 
CEIL(SYSDATE - ARPSA.DUE_DATE) >= -999 AND CEIL(SYSDATE - ARPSA.DUE_DATE) < 0 
THEN ARPSA.AMOUNT_DUE_REMAINING ELSE 0
END "CURRENT BUCKET",
CASE WHEN 
CEIL(SYSDATE - ARPSA.DUE_DATE) >= 0 AND CEIL(SYSDATE - ARPSA.DUE_DATE) < 30 
THEN ARPSA.AMOUNT_DUE_REMAINING ELSE 0
END "0 T0 30 DAYS",
CASE WHEN 
CEIL(SYSDATE - ARPSA.DUE_DATE) >= 31 AND CEIL(SYSDATE - ARPSA.DUE_DATE) < 60 
THEN ARPSA.AMOUNT_DUE_REMAINING ELSE 0
END "31 TO 60 DAYS",
CASE WHEN 
CEIL(SYSDATE - ARPSA.DUE_DATE) >= 61 AND CEIL(SYSDATE - ARPSA.DUE_DATE) < 90
THEN ARPSA.AMOUNT_DUE_REMAINING ELSE 0
END "61 TO 90 DAYS",
CASE WHEN 
CEIL(SYSDATE - ARPSA.DUE_DATE) >= 91 AND CEIL(SYSDATE - ARPSA.DUE_DATE) <  120
THEN ARPSA.AMOUNT_DUE_REMAINING ELSE 0
END "91 TO 120 DAYS",
CASE WHEN 
CEIL(SYSDATE - ARPSA.DUE_DATE) >= 121 AND CEIL(SYSDATE - ARPSA.DUE_DATE) < 999999
THEN ARPSA.AMOUNT_DUE_REMAINING ELSE 0
END "MORE THAN 120 DAYS"
--tables
FROM
HR_ALL_ORGANIZATION_UNITS HAOU,
HZ_PARTIES HZP,
RA_CUSTOMER_TRX_ALL RACTA,
AR_PAYMENT_SCHEDULES_ALL ARPSA

--joins and conditions
WHERE 1=1
AND RACTA.ORG_ID = HAOU.ORGANIZATION_ID(+)
AND RACTA.CUSTOMER_TRX_ID = ARPSA.CUSTOMER_TRX_ID(+)
AND RACTA.SOLD_TO_PARTY_ID = HZP.PARTY_ID(+)
AND ARPSA.AMOUNT_DUE_REMAINING > 0
AND ARPSA.AMOUNT_DUE_ORIGINAL - ARPSA.AMOUNT_DUE_REMAINING != 0

