CREATE TABLE R1 ( ID VARCHAR2(30),NAME VARCHAR2(40));

CREATE TABLE R2 (D_ID VARCHAR2(30),SALARY VARCHAR2(40),PLACE VARCHAR2(40));
INSERT INTO R1 VALUES('1','ROOPA');
INSERT INTO R1 VALUES('2','PM');
INSERT INTO R1 VALUES('3','PRITHVI');
INSERT INTO R1 VALUES('4','KAVIN');

INSERT INTO R2 VALUES('1','20000','MELUR');
INSERT INTO R2 VALUES('4','30000','MADURAI');
INSERT INTO R2 VALUES('5','20000','K.PATTI');
INSERT INTO R2 VALUES('2','20000','MELUR');
INSERT INTO R2 VALUES('1','20000','THENI');
commit;
select * from R1;
select * from R2;

SELECT * FROM R1 UNION SELECT * FROM R2;

SELECT ID,NAME,PLACE,SALARY FROM R1 A, R2 B WHERE A.ID(+)=B.D_ID;
SELECT ID,NAME,PLACE,SALARY FROM R1 A, R2 B WHERE A.ID=B.D_ID(+);
SELECT ID,NAME,PLACE,SALARY FROM R1 A, R2 B WHERE A.ID=B.D_ID;