SELECT 
ASSET_NUMBER,
TO_CHAR (INVOICE_DATE,'DD-Mon-YYYY','NLS_DATE_LANGUAGE = AMERICAN')INVOICE_DATE,
INVOICE_NUM,
TRANSFERRED_IN,
TRANSFERRED_OUT,
nvl(COST,0)+nvl(ADJ_COST,0)+nvl(cost_retired,0) AS_ON_CURRENT_YEAR,
DESCRIPTION,
(NVL(TRANSFERRED_IN,0)-NVL(TRANSFERRED_OUT,0)) BALANCE,
INVOICE_AMOUNT

FROM
(SELECT 
DISTINCT FAB.ASSET_NUMBER,
CASE WHEN  FTH.TRANSACTION_TYPE_CODE='CIP ADDITION' THEN TRANSACTION_DATE_ENTERED
ELSE NULL END INVOICE_DATE ,
(
select  distinct  AIA.INVOICE_NUM From FA_ASSET_INVOICES FAI,
ap_invoices_all AIA,
ap_invoice_lines_all AILA
where FAI.asset_id=fab.asset_id
and FAI.invoice_id=AIA.invoice_id
and FAI.invoice_id=AILA.invoice_id
and AILA.amount<>0
AND AIA.INVOICE_CURRENCY_CODE='SGD') INVOICE_NUM,
(
select  distinct  AIA.INVOICE_AMOUNT From FA_ASSET_INVOICES FAI,
ap_invoices_all AIA,
ap_invoice_lines_all AILA
where FAI.asset_id=fab.asset_id
and FAI.invoice_id=AIA.invoice_id
and FAI.invoice_id=AILA.invoice_id
and AILA.amount<>0
AND AIA.INVOICE_CURRENCY_CODE='SGD') INVOICE_AMOUNT,

 CASE WHEN FTH.TRANSACTION_TYPE_CODE='CIP ADDITION' THEN FB.COST 
 END TRANSFERRED_IN,
 CASE WHEN FTH.TRANSACTION_TYPE_CODE='ADDITION' THEN FB.COST
 END TRANSFERRED_OUT,
ADJ.ADJ_COST,
ret.cost_retired,
FATL.DESCRIPTION,
FB.COST
FROM
FA_ADDITIONS_B FAB,
FA_CATEGORIES_B FCB,
FA_ADDITIONS_TL FATL,
FA_TRANSACTION_HEADERS FTH,
FA_BOOKS FB,
(select asset_number, a.ASSET_ID,
sum(decode(DEBIT_CREDIT_FLAG,'CR',-nvl(ADJUSTMENT_AMOUNT,0),nvl(ADJUSTMENT_AMOUNT,0))) ADJ_COST 
From FA_ADJUSTMENTS a,FA_ADDITIONS_B b
-- FA_DEPRN_PERIODS FDP
where a.asset_id=b.asset_id 
-- and b.asset_number in ('610','611') 
and a.ADJUSTMENT_TYPE='COST'
and SOURCE_TYPE_CODE in ('ADDITION')
and  PERIOD_COUNTER_ADJUSTED in (
select PERIOD_COUNTER from FA_DEPRN_PERIODS FDP1 where
FISCAL_YEAR =(
select FISCAL_YEAR from FA_DEPRN_PERIODS FDP 
where PERIOD_NAME =:p_period_name and book_type_code=:P_books)
and PERIOD_COUNTER <= ( select PERIOD_COUNTER from FA_DEPRN_PERIODS FDP 
where PERIOD_NAME =:p_period_name and book_type_code=:P_books)
and book_type_code=:P_books
)
group by asset_number, a.ASSET_ID) ADJ,
(select b.asset_number,cost_retired FRom fa_retirements a,FA_ADDITIONS_B b
where a.asset_id=b.asset_id 
-- and b.asset_number in ('612') 
and exists ( select 1 from FA_DEPRN_PERIODS D
 where a.date_retired between D.CALENDAR_PERIOD_OPEN_DATE and D.CALENDAR_PERIOD_CLOSE_DATE 
and d.BOOK_TYPE_CODE=:P_books
and period_name=:p_period_name)
)RET

WHERE
FCB.CATEGORY_ID=FAB.ASSET_CATEGORY_ID
AND
FATL.ASSET_ID=FAB.ASSET_ID
AND
FTH.ASSET_ID=FAB.ASSET_ID
AND 
FB.ASSET_ID=FAB.ASSET_ID
AND 
FB.TRANSACTION_HEADER_ID_IN=FTH.TRANSACTION_HEADER_ID
AND 
FAB.ASSET_NUMBER=ADJ.ASSET_NUMBER(+)
AND
FAB.ASSET_NUMBER=RET.ASSET_NUMBER(+)
AND
TRANSACTION_TYPE_CODE IN ('ADDITION','CIP ADDITION')
)MAIN
WHERE
ASSET_NUMBER='580'

-- GROUP BY ASSET_NUMBER,DESCRIPTION,INVOICE_NUM,INVOICE_AMOUNT,TRANSFERRED_IN,
-- TRANSFERRED_OUT,INVOICE_DATE