CREATE TABLE TASK_8(LE_NAME VARCHAR2(100),BUSINESS_UNIT VARCHAR2(100),
COMPANY_ID VARCHAR2(100),CUSTOMER_NAME VARCHAR2(100));
INSERT INTO TASK_8 VALUES('LE1','BU1','200400','C1');
INSERT INTO TASK_8 VALUES('LE1','BU1','200402','C2');
INSERT INTO TASK_8 VALUES('LE1','BU1','200402','C1');
INSERT INTO TASK_8 VALUES('LE1','BU1','200403','C3');
INSERT INTO TASK_8 VALUES('LE1','BU1','200404','C3');
INSERT INTO TASK_8 VALUES('LE1','BU1','200405','C3');

SELECT * FROM TASK_8;
----SELECT COMPANY_ID,COUNT(COMPANY_ID),CUSTOMER_NAME,COUNT(CUSTOMER_NAME) AS REF FROM TASK_8 
----GROUP BY COMPANY_ID HAVING COUNT(COMPANY_ID) ;
--SELECT COMPANY_ID,CUSTOMER_NAME,COUNT(COMPANY_ID),COUNT(CUSTOMER_NAME)FROM TASK_8 GROUP BY COMPANY_ID,CUSTOMER_NAME 
--HAVING COUNT(COMPANY_ID)>0 AND COUNT(CUSTOMER_NAME)>0;
commit;
SELECT LE_NAME,BUSINESS_UNIT,COMPANY_ID,CUSTOMER_NAME, 
ROW_NUMBER() OVER (PARTITION BY CUSTOMER_NAME ORDER BY COMPANY_ID) AS REF FROM TASK_8 T;
